// Verified local CoinMarketCap logos. Provenance: public/coins/sources.json
export const coinLogos: Readonly<Record<string,string>> = {
  "AAVE": "/coins/aave.png",
  "ADA": "/coins/ada.png",
  "APT": "/coins/apt.png",
  "ARB": "/coins/arb.png",
  "AVAX": "/coins/avax.png",
  "BCH": "/coins/bch.png",
  "BNB": "/coins/bnb.png",
  "BTC": "/coins/btc.png",
  "DAI": "/coins/dai.png",
  "DOGE": "/coins/doge.png",
  "DOT": "/coins/dot.png",
  "ETH": "/coins/eth.png",
  "FDUSD": "/coins/fdusd.png",
  "LINK": "/coins/link.png",
  "LTC": "/coins/ltc.png",
  "NEAR": "/coins/near.png",
  "OP": "/coins/op.png",
  "PYUSD": "/coins/pyusd.png",
  "SOL": "/coins/sol.png",
  "SUI": "/coins/sui.png",
  "TON": "/coins/ton.png",
  "TRX": "/coins/trx.png",
  "TUSD": "/coins/tusd.png",
  "UNI": "/coins/uni.png",
  "USDC": "/coins/usdc.png",
  "USDP": "/coins/usdp.png",
  "USDT": "/coins/usdt.png",
  "WBTC": "/coins/wbtc.png",
  "WETH": "/coins/weth.png",
  "XRP": "/coins/xrp.png"
};
